### ISSUE TITLE
URGENT BUG: Some players are no longer able to log in

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#100]
![grafik](https://user-images.githubusercontent.com/22304202/213694530-e2c3c9b6-3662-4bb6-975d-13b3e1a6f9b6.png)

**Comment by panwauu** [comment]
I can still log in and see people logged in. Any usernames for which it does not work?

**Comment by gereon77** [comment]
Mine.. but it looks like it was a temporary issue. It happened to my account on 2 devices but after the 20th try it works now.
