### ISSUE TITLE
Bug: Server created two similar games after players passed the ready check

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#104]
![image](https://user-images.githubusercontent.com/22304202/220124570-db073ce5-9272-4caf-92a4-7155d1893263.png)

Leichtfuss reported, that suddenly two games were running and the players were were spread over 2 rooms and were not able to play.

GameIds: 37525 and 37524

**Comment by panwauu** [comment]
Hi Gereon,
This is a known problem which happens from time to time (#72). 
I was not able to reproduce it or to find the error in the code.
I would be very happy for a second opinion!
Here is the implementation of the game creation: https://github.com/panwauu/tac-with-bug/blob/9c7680f7fd293537ba7231929297c6adbadab8d1/server/src/services/game.ts#L104
Strangely, I need a auxiliary function to change the order of the players I guess:
https://github.com/panwauu/tac-with-bug/blob/d24bdac74449019ee7c54b6c2653ff3f3105bada/server/src/socket/waiting.ts#L174
Here the game is created if the last players sets the state to ready:
https://github.com/panwauu/tac-with-bug/blob/d24bdac74449019ee7c54b6c2653ff3f3105bada/server/src/socket/waiting.ts#L108

**Comment by panwauu** [comment]
Close as stale
