### ISSUE TITLE
Enhancement: Add an option to play the game without HUD assistance

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#105]
I played a real world game on tabletop last weekend and realized that I miss the preview on TWB's HUD of where the marbles will eventually arrive. The ability to click through each card and marble to preview all the possibilities is very useful, but it weakens your real game skillz. An option to disable this assistance (I think for everyone then to make it fair) could help to train for real games tournaments.

**Comment by panwauu** [comment]
I am personally not sure if this is an option worth implementing. The rule checking cannot be disabled anyways in game.

**Comment by gereon77** [comment]
> I am personally not sure if this is an option worth implementing. The rule checking cannot be disabled anyways in game.

Of course you must not be allowed to do illegal moves. I only think I would prefer to disable the preview visualization…
