### ISSUE TITLE
Bug: Strange 3p game

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#76]
Affected game:

https://tac-with-bug.herokuapp.com/#/en/game?gameID=31483&nPlayers=3

This lobby looked weird to me and I wanted to spectate whats going on:
![image](https://user-images.githubusercontent.com/22304202/202460655-0f7afeb0-9e90-4d62-a036-b0334f27ba16.png)

Though I am just spectating, it shows me as player:
![image](https://user-images.githubusercontent.com/22304202/202460476-9e06ce03-0455-47f5-bf08-f06114957b01.png)

**Comment by panwauu** [comment]
Looks wierd. Seems like one player deleted the profile or was not properly linked to a running game. I also need to investigate the spectator mode it seems

**Comment by panwauu** [comment]
Closed as the issue seems to be stale
