### ISSUE TITLE
Bug: Substitution is only working for the player who has to move next, not for the waited for player

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#78]
This is problematic if a player drops out during card swapping state. We wait for lets say player A here, who has not swapped yet but the game only offers a substitution for player B who is the one who would start the next round and play as first... I hope this description is sufficient to describe the issue.

**Comment by panwauu** [comment]
Good catch!
I forgot the state of card trading which can happen at the beginning of a round and during narr. Maybe even during the teufel?
I have to think about it

**Comment by gereon77** [comment]
> Good catch! I forgot the state of card trading which can happen at the beginning of a round and during narr. Maybe even during the teufel? I have to think about it

Yea.. Additionally, just a minor issue... The substitution alert pops up as well when game is finished and when you stay in the game longer than a minute to read stats or to chat with the players...

**Comment by panwauu** [comment]
ToDos:
- [ ] Server: Fix condition to allow to trade during trade/narr
- [ ] Server: Test condition to allow during trade
- [ ] Server: Test condition to allow during narr
- [ ] Server: Test condition to allow during teufel
- [ ] Client: Remove pop up after game ended
- [ ] Client: Add pop up if trade/narr
- [ ] Client: Test after game
- [ ] Client: Test during trade
- [ ] Client: Test during narr
- [ ] Client: Test during teufel
