### ISSUE TITLE
Enhancement: Use Math.round instead if Math.floor for calculating statistics

### ISSUE THREAD

**Issue by gereon77** [panwauu/tac-with-bug#88]
I just wondered how long it will take to reach a success rate of 58% and I calculated my current one and came to 57,54 % which looks to me you’re using Math.floor instead of round…

**Comment by gereon77** [comment]
I checked the code and it's using Math.round already. Still I don't know why it shows 57 though it should show 58...

**Comment by panwauu** [comment]
Currently you are at 173/302=0,573 and success rate of 57%

Closing this until further evidence 😉

PS: Danke für das mitdenken und mitarbeiten. Manche Fehler kommen gar nicht mehr bei mir an

**Comment by gereon77** [comment]
@panwauu : This means you're counting aborted games as lost games?
